name: CI Build

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release